// Centralized product data
export const allProducts = [
    // Dresses
    { id: 1, name: "Amalfi Slub Dip-Dye", price: 68.00, image: "/images/shop-products/product1.png", category: "Dresses", sku: "LA-1234", tags: ["Dress", "Clothing"], description: "Aenean et tortor at risus viverra. Commodo nulla facilisi nullam vehicula ipsum. Ultricies mi eget mauris pharetra et ultrices neque ornare." },
    { id: 2, name: "Nicola Crinkle Tier", price: 78.00, image: "/images/shop-products/product3.png", category: "Dresses", sku: "LA-1235", tags: ["Dress", "Clothing"], description: "Aenean et tortor at risus viverra. Commodo nulla facilisi nullam vehicula ipsum. Ultricies mi eget mauris pharetra et ultrices neque ornare." },
    { id: 3, name: "Silk Evening Dress", price: 120.00, image: "/images/shop-products/product2.png", category: "Dresses", sku: "LA-1236", tags: ["Dress", "Clothing"], description: "Aenean et tortor at risus viverra. Commodo nulla facilisi nullam vehicula ipsum. Ultricies mi eget mauris pharetra et ultrices neque ornare." },
    { id: 4, name: "Casual Cotton Dress", price: 55.00, image: "/images/shop-products/product3.png", category: "Dresses", sku: "LA-1237", tags: ["Dress", "Clothing"], description: "Aenean et tortor at risus viverra. Commodo nulla facilisi nullam vehicula ipsum. Ultricies mi eget mauris pharetra et ultrices neque ornare." },
    { id: 5, name: "Beach Dress", price: 62.00, image: "/images/shop-products/product1.png", category: "Dresses", sku: "LA-1238", tags: ["Dress", "Clothing"], description: "Aenean et tortor at risus viverra. Commodo nulla facilisi nullam vehicula ipsum. Ultricies mi eget mauris pharetra et ultrices neque ornare." },
    { id: 6, name: "Maxi Dress", price: 85.00, image: "/images/shop-products/product3.png", category: "Dresses", sku: "LA-1239", tags: ["Dress", "Clothing"], description: "Aenean et tortor at risus viverra. Commodo nulla facilisi nullam vehicula ipsum. Ultricies mi eget mauris pharetra et ultrices neque ornare." },
    { id: 7, name: "Floral Print Dress", price: 72.00, image: "/images/shop-products/product1.png", category: "Dresses", sku: "LA-1240", tags: ["Dress", "Clothing"], description: "Aenean et tortor at risus viverra. Commodo nulla facilisi nullam vehicula ipsum. Ultricies mi eget mauris pharetra et ultrices neque ornare." },
    { id: 8, name: "Cocktail Dress", price: 98.00, image: "/images/shop-products/product3.png", category: "Dresses", sku: "LA-1241", tags: ["Dress", "Clothing"], description: "Aenean et tortor at risus viverra. Commodo nulla facilisi nullam vehicula ipsum. Ultricies mi eget mauris pharetra et ultrices neque ornare." },
    { id: 9, name: "Wrap Dress", price: 65.00, image: "/images/shop-products/product1.png", category: "Dresses", sku: "LA-1242", tags: ["Dress", "Clothing"], description: "Aenean et tortor at risus viverra. Commodo nulla facilisi nullam vehicula ipsum. Ultricies mi eget mauris pharetra et ultrices neque ornare." },
    { id: 10, name: "Summer Sundress", price: 58.00, image: "/images/shop-products/product2.png", category: "Dresses", sku: "LA-1243", tags: ["Dress", "Clothing"], description: "Aenean et tortor at risus viverra. Commodo nulla facilisi nullam vehicula ipsum. Ultricies mi eget mauris pharetra et ultrices neque ornare." },
    { id: 11, name: "Bodycon Dress", price: 75.00, image: "/images/shop-products/product3.png", category: "Dresses", sku: "LA-1244", tags: ["Dress", "Clothing"], description: "Aenean et tortor at risus viverra. Commodo nulla facilisi nullam vehicula ipsum. Ultricies mi eget mauris pharetra et ultrices neque ornare." },
    { id: 12, name: "A-Line Dress", price: 82.00, image: "/images/shop-products/product1.png", category: "Dresses", sku: "LA-1245", tags: ["Dress", "Clothing"], description: "Aenean et tortor at risus viverra. Commodo nulla facilisi nullam vehicula ipsum. Ultricies mi eget mauris pharetra et ultrices neque ornare." },
    { id: 13, name: "Vintage Midi Dress", price: 92.00, image: "/images/shop-products/product2.png", category: "Dresses", sku: "LA-1246", tags: ["Dress", "Clothing"], description: "Aenean et tortor at risus viverra. Commodo nulla facilisi nullam vehicula ipsum. Ultricies mi eget mauris pharetra et ultrices neque ornare." },

    // Tops
    { id: 14, name: "Varley Triblend", price: 88.00, image: "/images/shop-products/product2.png", category: "Tops", sku: "LA-2001", tags: ["Top", "Clothing"], description: "Aenean et tortor at risus viverra. Commodo nulla facilisi nullam vehicula ipsum. Ultricies mi eget mauris pharetra et ultrices neque ornare." },
    { id: 15, name: "Summer Tank Top", price: 45.00, image: "/images/shop-products/product1.png", category: "Tops", sku: "LA-2002", tags: ["Top", "Clothing"], description: "Aenean et tortor at risus viverra. Commodo nulla facilisi nullam vehicula ipsum. Ultricies mi eget mauris pharetra et ultrices neque ornare." },
    { id: 16, name: "Crop Top", price: 38.00, image: "/images/shop-products/product2.png", category: "Tops", sku: "LA-2003", tags: ["Top", "Clothing"], description: "Aenean et tortor at risus viverra. Commodo nulla facilisi nullam vehicula ipsum. Ultricies mi eget mauris pharetra et ultrices neque ornare." },
    { id: 17, name: "Oversized Tee", price: 42.00, image: "/images/shop-products/product2.png", category: "Tops", sku: "LA-2004", tags: ["Top", "Clothing"], description: "Aenean et tortor at risus viverra. Commodo nulla facilisi nullam vehicula ipsum. Ultricies mi eget mauris pharetra et ultrices neque ornare." },
    { id: 18, name: "Button Down Shirt", price: 52.00, image: "/images/shop-products/product2.png", category: "Tops", sku: "LA-2005", tags: ["Top", "Clothing"], description: "Aenean et tortor at risus viverra. Commodo nulla facilisi nullam vehicula ipsum. Ultricies mi eget mauris pharetra et ultrices neque ornare." },
    { id: 19, name: "Silk Blouse", price: 95.00, image: "/images/shop-products/product1.png", category: "Tops", sku: "LA-2006", tags: ["Top", "Clothing"], description: "Aenean et tortor at risus viverra. Commodo nulla facilisi nullam vehicula ipsum. Ultricies mi eget mauris pharetra et ultrices neque ornare." },
    { id: 20, name: "Striped Tee", price: 35.00, image: "/images/shop-products/product2.png", category: "Tops", sku: "LA-2007", tags: ["Top", "Clothing"], description: "Aenean et tortor at risus viverra. Commodo nulla facilisi nullam vehicula ipsum. Ultricies mi eget mauris pharetra et ultrices neque ornare." },
    { id: 21, name: "V-Neck Sweater", price: 68.00, image: "/images/shop-products/product1.png", category: "Tops", sku: "LA-2008", tags: ["Top", "Clothing"], description: "Aenean et tortor at risus viverra. Commodo nulla facilisi nullam vehicula ipsum. Ultricies mi eget mauris pharetra et ultrices neque ornare." },
    { id: 22, name: "Polo Shirt", price: 48.00, image: "/images/shop-products/product2.png", category: "Tops", sku: "LA-2009", tags: ["Top", "Clothing"], description: "Aenean et tortor at risus viverra. Commodo nulla facilisi nullam vehicula ipsum. Ultricies mi eget mauris pharetra et ultrices neque ornare." },
    { id: 23, name: "Graphic Tee", price: 32.00, image: "/images/shop-products/product1.png", category: "Tops", sku: "LA-2010", tags: ["Top", "Clothing"], description: "Aenean et tortor at risus viverra. Commodo nulla facilisi nullam vehicula ipsum. Ultricies mi eget mauris pharetra et ultrices neque ornare." },

    // Bottoms
    { id: 24, name: "Denim Jeans", price: 75.00, image: "/images/shop-products/product1.png", category: "Bottoms", sku: "LA-3001", tags: ["Bottom", "Clothing"], description: "Aenean et tortor at risus viverra. Commodo nulla facilisi nullam vehicula ipsum. Ultricies mi eget mauris pharetra et ultrices neque ornare." },
    { id: 25, name: "Wide Leg Pants", price: 70.00, image: "/images/shop-products/product1.png", category: "Bottoms", sku: "LA-3002", tags: ["Bottom", "Clothing"], description: "Aenean et tortor at risus viverra. Commodo nulla facilisi nullam vehicula ipsum. Ultricies mi eget mauris pharetra et ultrices neque ornare." },
    { id: 26, name: "High Waist Shorts", price: 48.00, image: "/images/shop-products/product1.png", category: "Bottoms", sku: "LA-3003", tags: ["Bottom", "Clothing"], description: "Aenean et tortor at risus viverra. Commodo nulla facilisi nullam vehicula ipsum. Ultricies mi eget mauris pharetra et ultrices neque ornare." },
    { id: 27, name: "Midi Skirt", price: 58.00, image: "/images/shop-products/product3.png", category: "Bottoms", sku: "LA-3004", tags: ["Bottom", "Clothing"], description: "Aenean et tortor at risus viverra. Commodo nulla facilisi nullam vehicula ipsum. Ultricies mi eget mauris pharetra et ultrices neque ornare." },
    { id: 28, name: "Pleated Trousers", price: 85.00, image: "/images/shop-products/product2.png", category: "Bottoms", sku: "LA-3005", tags: ["Bottom", "Clothing"], description: "Aenean et tortor at risus viverra. Commodo nulla facilisi nullam vehicula ipsum. Ultricies mi eget mauris pharetra et ultrices neque ornare." },
    { id: 29, name: "Cargo Pants", price: 65.00, image: "/images/shop-products/product1.png", category: "Bottoms", sku: "LA-3006", tags: ["Bottom", "Clothing"], description: "Aenean et tortor at risus viverra. Commodo nulla facilisi nullam vehicula ipsum. Ultricies mi eget mauris pharetra et ultrices neque ornare." },
    { id: 30, name: "Mini Skirt", price: 45.00, image: "/images/shop-products/product3.png", category: "Bottoms", sku: "LA-3007", tags: ["Bottom", "Clothing"], description: "Aenean et tortor at risus viverra. Commodo nulla facilisi nullam vehicula ipsum. Ultricies mi eget mauris pharetra et ultrices neque ornare." },
    { id: 31, name: "Leather Pants", price: 125.00, image: "/images/shop-products/product2.png", category: "Bottoms", sku: "LA-3008", tags: ["Bottom", "Clothing"], description: "Aenean et tortor at risus viverra. Commodo nulla facilisi nullam vehicula ipsum. Ultricies mi eget mauris pharetra et ultrices neque ornare." },
    { id: 32, name: "Joggers", price: 55.00, image: "/images/shop-products/product1.png", category: "Bottoms", sku: "LA-3009", tags: ["Bottom", "Clothing"], description: "Aenean et tortor at risus viverra. Commodo nulla facilisi nullam vehicula ipsum. Ultricies mi eget mauris pharetra et ultrices neque ornare." },

    // Jewelry
    { id: 33, name: "Gold Necklace", price: 150.00, image: "/images/shop-products/product2.png", category: "Jewelry", sku: "LA-4001", tags: ["Jewelry", "Accessories"], description: "Aenean et tortor at risus viverra. Commodo nulla facilisi nullam vehicula ipsum. Ultricies mi eget mauris pharetra et ultrices neque ornare." },
    { id: 34, name: "Pearl Earrings", price: 130.00, image: "/images/shop-products/product2.png", category: "Jewelry", sku: "LA-4002", tags: ["Jewelry", "Accessories"], description: "Aenean et tortor at risus viverra. Commodo nulla facilisi nullam vehicula ipsum. Ultricies mi eget mauris pharetra et ultrices neque ornare." },
    { id: 35, name: "Diamond Ring", price: 250.00, image: "/images/shop-products/product2.png", category: "Jewelry", sku: "LA-4003", tags: ["Jewelry", "Accessories"], description: "Aenean et tortor at risus viverra. Commodo nulla facilisi nullam vehicula ipsum. Ultricies mi eget mauris pharetra et ultrices neque ornare." },
    { id: 36, name: "Silver Bracelet", price: 95.00, image: "/images/shop-products/product3.png", category: "Jewelry", sku: "LA-4004", tags: ["Jewelry", "Accessories"], description: "Aenean et tortor at risus viverra. Commodo nulla facilisi nullam vehicula ipsum. Ultricies mi eget mauris pharetra et ultrices neque ornare." },
    { id: 37, name: "Charm Necklace", price: 110.00, image: "/images/shop-products/product1.png", category: "Jewelry", sku: "LA-4005", tags: ["Jewelry", "Accessories"], description: "Aenean et tortor at risus viverra. Commodo nulla facilisi nullam vehicula ipsum. Ultricies mi eget mauris pharetra et ultrices neque ornare." },
    { id: 38, name: "Hoop Earrings", price: 75.00, image: "/images/shop-products/product2.png", category: "Jewelry", sku: "LA-4006", tags: ["Jewelry", "Accessories"], description: "Aenean et tortor at risus viverra. Commodo nulla facilisi nullam vehicula ipsum. Ultricies mi eget mauris pharetra et ultrices neque ornare." },
    { id: 39, name: "Anklet Set", price: 45.00, image: "/images/shop-products/product3.png", category: "Jewelry", sku: "LA-4007", tags: ["Jewelry", "Accessories"], description: "Aenean et tortor at risus viverra. Commodo nulla facilisi nullam vehicula ipsum. Ultricies mi eget mauris pharetra et ultrices neque ornare." },
    { id: 40, name: "Statement Ring", price: 180.00, image: "/images/shop-products/product1.png", category: "Jewelry", sku: "LA-4008", tags: ["Jewelry", "Accessories"], description: "Aenean et tortor at risus viverra. Commodo nulla facilisi nullam vehicula ipsum. Ultricies mi eget mauris pharetra et ultrices neque ornare." },
    { id: 41, name: "Layered Necklace", price: 120.00, image: "/images/shop-products/product2.png", category: "Jewelry", sku: "LA-4009", tags: ["Jewelry", "Accessories"], description: "Aenean et tortor at risus viverra. Commodo nulla facilisi nullam vehicula ipsum. Ultricies mi eget mauris pharetra et ultrices neque ornare." },
    { id: 42, name: "Stud Earrings", price: 65.00, image: "/images/shop-products/product3.png", category: "Jewelry", sku: "LA-4010", tags: ["Jewelry", "Accessories"], description: "Aenean et tortor at risus viverra. Commodo nulla facilisi nullam vehicula ipsum. Ultricies mi eget mauris pharetra et ultrices neque ornare." },
    { id: 43, name: "Tennis Bracelet", price: 220.00, image: "/images/shop-products/product1.png", category: "Jewelry", sku: "LA-4011", tags: ["Jewelry", "Accessories"], description: "Aenean et tortor at risus viverra. Commodo nulla facilisi nullam vehicula ipsum. Ultricies mi eget mauris pharetra et ultrices neque ornare." },
    { id: 44, name: "Pendant Necklace", price: 98.00, image: "/images/shop-products/product2.png", category: "Jewelry", sku: "LA-4012", tags: ["Jewelry", "Accessories"], description: "Aenean et tortor at risus viverra. Commodo nulla facilisi nullam vehicula ipsum. Ultricies mi eget mauris pharetra et ultrices neque ornare." },

    // Sun Glasses
    { id: 45, name: "Designer Sunglasses", price: 95.00, image: "/images/shop-products/product3.png", category: "Sun Glasses", sku: "LA-5001", tags: ["Sunglasses", "Accessories"], description: "Aenean et tortor at risus viverra. Commodo nulla facilisi nullam vehicula ipsum. Ultricies mi eget mauris pharetra et ultrices neque ornare." },
    { id: 46, name: "Aviator Sunglasses", price: 110.00, image: "/images/shop-products/product3.png", category: "Sun Glasses", sku: "LA-5002", tags: ["Sunglasses", "Accessories"], description: "Aenean et tortor at risus viverra. Commodo nulla facilisi nullam vehicula ipsum. Ultricies mi eget mauris pharetra et ultrices neque ornare." },
    { id: 47, name: "Cat Eye Sunglasses", price: 88.00, image: "/images/shop-products/product3.png", category: "Sun Glasses", sku: "LA-5003", tags: ["Sunglasses", "Accessories"], description: "Aenean et tortor at risus viverra. Commodo nulla facilisi nullam vehicula ipsum. Ultricies mi eget mauris pharetra et ultrices neque ornare." },
    { id: 48, name: "Round Frame Sunglasses", price: 78.00, image: "/images/shop-products/product2.png", category: "Sun Glasses", sku: "LA-5004", tags: ["Sunglasses", "Accessories"], description: "Aenean et tortor at risus viverra. Commodo nulla facilisi nullam vehicula ipsum. Ultricies mi eget mauris pharetra et ultrices neque ornare." },
    { id: 49, name: "Oversized Sunglasses", price: 105.00, image: "/images/shop-products/product1.png", category: "Sun Glasses", sku: "LA-5005", tags: ["Sunglasses", "Accessories"], description: "Aenean et tortor at risus viverra. Commodo nulla facilisi nullam vehicula ipsum. Ultricies mi eget mauris pharetra et ultrices neque ornare." },
    { id: 50, name: "Sport Sunglasses", price: 85.00, image: "/images/shop-products/product3.png", category: "Sun Glasses", sku: "LA-5006", tags: ["Sunglasses", "Accessories"], description: "Aenean et tortor at risus viverra. Commodo nulla facilisi nullam vehicula ipsum. Ultricies mi eget mauris pharetra et ultrices neque ornare." },
    { id: 51, name: "Retro Sunglasses", price: 92.00, image: "/images/shop-products/product2.png", category: "Sun Glasses", sku: "LA-5007", tags: ["Sunglasses", "Accessories"], description: "Aenean et tortor at risus viverra. Commodo nulla facilisi nullam vehicula ipsum. Ultricies mi eget mauris pharetra et ultrices neque ornare." },
    { id: 52, name: "Polarized Sunglasses", price: 125.00, image: "/images/shop-products/product1.png", category: "Sun Glasses", sku: "LA-5008", tags: ["Sunglasses", "Accessories"], description: "Aenean et tortor at risus viverra. Commodo nulla facilisi nullam vehicula ipsum. Ultricies mi eget mauris pharetra et ultrices neque ornare." },
    { id: 53, name: "Mirrored Sunglasses", price: 98.00, image: "/images/shop-products/product3.png", category: "Sun Glasses", sku: "LA-5009", tags: ["Sunglasses", "Accessories"], description: "Aenean et tortor at risus viverra. Commodo nulla facilisi nullam vehicula ipsum. Ultricies mi eget mauris pharetra et ultrices neque ornare." },
    { id: 54, name: "Wayfarer Sunglasses", price: 115.00, image: "/images/shop-products/product2.png", category: "Sun Glasses", sku: "LA-5010", tags: ["Sunglasses", "Accessories"], description: "Aenean et tortor at risus viverra. Commodo nulla facilisi nullam vehicula ipsum. Ultricies mi eget mauris pharetra et ultrices neque ornare." },
];

// Helper function to create URL-friendly slugs
export function createSlug(name) {
    return name.toLowerCase().replace(/\s+/g, '-').replace(/[^a-z0-9-]/g, '');
}

// Helper function to get product by slug
export function getProductBySlug(slug) {
    return allProducts.find(product => createSlug(product.name) === slug);
}